spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: hoon
    password: hoon
  application:
    name: review-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9093
#  port: 8083