spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: hoon
    password: hoon
  application:
    name: review-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

server:
  port: 8083