spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# actuator.md ?? ??, ??? ??? ??? ???? ????? ??? ???? ?? ?? ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    # /health endpoint ?? ? ? ?? ?? ??
    health:
      show-details: always
    shutdown:
      enabled: true

info:
  app:
    name: JobApplication
    description: Job App
    version: 1.0.0