spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes: # yml 에서 배열 표현 시 - 사용
        - id: company_service
          uri: http://company:9090
          predicates:
            - Path=/companies/**
        - id: job_service
          uri: http://job:9091
          predicates:
            - Path=/jobs/**
        - id: review_service
          uri: http://review:9093
          predicates:
            - Path=/reviews/**
        - id: eureka-server
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/ # http://localhost:8761/eureka/main -> http://localhost:8761/ 로 변경
        - id: eureka-server-static # eureka css 가 안나오는 경우 설정
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/**

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
#  port: 8084
  port: 9094

