spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: hoon
    password: hoon
  application:
    name: company-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

job-service:
  url: http://job:9091

coMpany-service:
  url: http://company:9090

review-service:
  url: http://review:9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 9090
#  port: 8081