spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: hoon
    password: hoon
  application:
    name: company-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9090
#  port: 8081