spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false # ???? Eureka ??? ????? ?? ??? ? ?? ????? ??
    fetch-registry: false # ????? Eureka ??? ??? ????? ??? ???? ??

server:
  port: 8761
