spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: hoon
    password: hoon

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

server:
  port: 8082

