spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: hoon
    password: hoon
  application:
    name: job-service

  # config 를 통해 config server 의 application.name 을 가져올 수 있음
  # optional 을 사용하면 config 서버가 죽었을 때 현재 yml의 설정을 가져와 에러를 피할 수 있음
  config:
    import: optional:configserver:http://localhost:8080
  profiles:
    active: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

# Eureka
# 아래 설정은 없어도 유레카에 자동으로 등록된다
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082